baseURL = 'https://hckweb.github.io/'
languageCode = 'en-us'
title = 'Cem KOC'

theme = "hugo-ficurinia"

author = "Cem KOC"
copyright = "This work by [Cem KOC](https://hckweb.github.io/) is licensed under [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). ![CC BY](https://mirrors.creativecommons.org/presskit/buttons/80x15/svg/by.svg)"

[params]
    author = "Cem KOC"
    description = "Cem KOC's personal blog"
    
    tagsInArticlePreview = true
    menuStyle = "buttons"
    inputStyle = "buttons"
    mobileHamburgerNav = true

    enableRelatedArticles = true

    logo = "/logo.svg"
    favicon = "/favicon.png"  # 32x32
    faviconIco = "/favicon.ico"  # 32x32
    appletouch = "/apple-touch-icon.png"  # 180x180
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"  # 512x512 png image

[menu]
    [[menu.icons]]
        identifier = "email"
        name = "Mail"
        url = "mailto:cem@hcemkoc.com"
        weight = 1
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/hckweb"
        weight = 2
    [[menu.icons]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/hüseyin-cem-koç"
        weight = 3

[outputs]
    home = ["HTML", "JSON"]
